obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /f_scan, marking: true, clearing: true, max_obstacle_height: 2.0, min_obstacle_height: 0.0}

inflation_layer:
  inflation_radius: 0.55
  cost_scaling_factor: 10.0

static_layer:
  map_topic: /map
  subscribe_to_updates: false

planner_frequency: 1.0
planner_patience: 5.0
controller_frequency: 5.0
controller_patience: 15.0

recovery_behavior_enabled: true
clearing_rotation_allowed: true

NavfnROS:
  allow_unknown: true
  default_tolerance: 0.3

DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 2.0

  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.2

  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 10
  vy_samples: 0
  vth_samples: 20

  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.05

  publish_traj_pc: true
  publish_cost_grid_pc: true